### ISSUE TITLE
panic: rmq redis error is not nil EOF

### ISSUE THREAD

**Issue by xiaobin** [adjust/rmq#30] opened 2017-12-12 05:10 UTC
I run batch_consumer.go,Regular report：panic: rmq redis error is not nil EOF

**Comment by wellle** [comment] 2017-12-12 11:13
That sounds like your Redis connection got closed unexpectedly.

**Comment by wellle** [comment] 2020-05-01 19:56
Closing as there's nothing to be done here. Possibly duplicate of #8.

**Closed by wellle** 2020-05-01 19:56 UTC
