### ISSUE TITLE
redis cluster - CROSSSLOT error

### ISSUE THREAD

**Issue by obh** [adjust/rmq#113] opened 2022-03-03 12:04 UTC
I was trying out the library against a redis cluster. With the last change, I am able to connect to the cluster but when I initiate the consumer I get the following errors - `consume error: rmq.ConsumeError (8): CROSSSLOT Keys in request don't hash to the same slot`. I'm guessing we are using keys which get hashed to different slots in the cluster and which is causing this issue. 

I haven't looked at the code in a lot of detail, but I want to know if it worked for @si3nloong since he had raised the last merged PR.

**Comment by wellle** [comment] 2022-03-03 15:27
It seems that redis uses characters `{` and `}` to use part of the key for hashing. See https://redis.io/topics/cluster-spec#keys-hash-tags

In rmq we currently use `[` and `]` for that. See file `redis_keys.go`. What you could try is replacing those characters with `{` and `}` and see if it works then. I think it might.

Please let us know if that works for you :v:

**Comment by obh** [comment] 2022-03-03 18:11
Yes, it's working. I just replaced the [] with the {}, didn't fully grasp what all the keys were used for though :). do you want me to send a PR on this? I had noticed that the older changes are also still in master, any plans to cut a new version say a 4.0.3? 
Anyway pushing to master should suffice as I plan to test some more. Will report back if I see any issues.

**Comment by obh** [comment] 2022-03-09 18:52
just to report back on this, while this change is required we also need to move away from using a redis client to using a redis clusterclient. This is because with a cluster the key could be moved to a different shard. As a result the redis client throws the error `MOVED 7652 10.0.4.210:6379`. 
The redis cluster client is equipped to follow this and connect with the right shard. I believe the underlying implementation of rediswrapper would need to change to support this. Anyways, I am forking out the repo and will change the redis client to cluster client. Will report back if I see any other issues. If none, maybe that's a path to still use this library with a redis cluster🤞

**Comment by NikhilRyan** [comment] 2023-06-21 13:02
> Yes, it's working. I just replaced the [] with the {}, didn't fully grasp what all the keys were used for though :). do you want me to send a PR on this? I had noticed that the older changes are also still in master, any plans to cut a new version say a 4.0.3? Anyway pushing to master should suffice as I plan to test some more. Will report back if I see any issues.

Is this fix merged? I'm getting the same error.
`2023/06/21 12:30:44 consume error: rmq.ConsumeError (8970): CROSSSLOT Keys in request don't hash to the same slot`

**Comment by wellle** [comment] 2023-06-21 14:53
No it hasn't been merged. See the comments in the closed PR linked above. There are still a few things which were not addressed yet.

**Comment by NikhilRyan** [comment] 2023-06-22 08:15
Thanks for your response. Just wanted to check if there is any work around until this issue got fixed?

**Comment by wellle** [comment] 2023-06-22 09:36
You know what, I'll try to look at the PR in the next few days and see if I can finish it. In that case, would you be up for testing it before we merge it?

**Comment by NikhilRyan** [comment] 2023-06-22 09:46
Yes, sure. That will be great. Thanks a lot

**Comment by wellle** [comment] 2023-06-27 16:04
Hey, quick update: I started working on this today and made good progress. I should be able to open a PR soon.

(Here's the work in progress branch: [113-redis-cluster-support](https://github.com/adjust/rmq/compare/113-redis-cluster-support))

**Comment by NikhilRyan** [comment] 2023-06-28 06:17
> Hey, quick update: I started working on this today and made good progress. I should be able to open a PR soon.
> 
> (Here's the work in progress branch: [113-redis-cluster-support](https://github.com/adjust/rmq/compare/113-redis-cluster-support))

That's great. Thanks for picking this up. Looking forward to it.

**Comment by wellle** [comment] 2023-06-29 21:55
Here's a new PR: https://github.com/adjust/rmq/pull/148

Please give it a try and let me know how it went! 🙏

**Comment by NikhilRyan** [comment] 2023-07-03 06:39
> Here's a new PR: #148
> 
> Please give it a try and let me know how it went! 🙏

Thanks for sharing. Let me test and revert with the update.

**Comment by NikhilRyan** [comment] 2023-07-05 11:23
Hi @wellle 
Thanks for your time, I've successfully tested #148 on a Redis Cluster environment. It is working for me. 
Request you to proceed with your PR.
Also, if it is possible for you to provide a timeline on the same so that I can communicate the same to my team from when they'll be able to use the Redis Cluster client.

Apart from this I have a small doubt, What will happen to the existing messages in the queue once we restart the service. I didn't see the previous messages from the queue when I restart my service.

Once again, thanks for your efforts and time.

**Comment by NikhilRyan** [comment] 2023-07-12 12:37
Hi @wellle, I hope you're doing well. Just wanted to check if there's any update/progress here?

**Comment by wellle** [comment] 2023-07-12 13:06
Hey, we're still working on making the tests work with Redis cluster.

**Comment by NikhilRyan** [comment] 2023-07-19 09:34
Hi @wellle, I hope you're doing well. Just wanted to check if there's any update/progress here?
Team has done all the dev using this library and now we don't want to switch to some other library.

**Comment by NikhilRyan** [comment] 2023-07-20 05:34
Hi @wellle, I can see #148 has passed all the checks and @vearutop has also approved the changes. What is the next step now?

**Comment by vearutop** [comment] 2023-07-20 06:17
Perhaps I can go ahead and merge that PR, since @wellle is out of office for a few days.

**Comment by vearutop** [comment] 2023-07-20 06:18
@NikhilRyan do you need a new version urgently?

**Comment by NikhilRyan** [comment] 2023-07-20 06:38
Hi @vearutop, thanks for reverting. 
Yes, one of my release is pending due to this. Would be great if this got merged.

**Closed** 2023-07-20 09:50 UTC

**Comment by vearutop** [comment] 2023-07-20 10:12
@NikhilRyan please try the new [`v5.2.0`](https://github.com/adjust/rmq/releases/tag/v5.2.0).

**Comment by wellle** [comment] 2023-07-24 12:10
Thank you for your support on this! And thanks to @vearutop too for finishing and releasing this version! 🙌 

The main thing to watch out for is to have exactly once queue cleaner instance per queue system (usually exactly one). You should be free to create as many consumers as you like and use as many queues as you like.

**Comment by NikhilRyan** [comment] 2023-07-28 06:29
Hi @wellle @vearutop, I hope you're guys are doing well. 
I've experienced an issue recently. I have two workers for a queue and it seems that consumer is picking half of the values only. Any idea why this could be happening?

**Comment by wellle** [comment] 2023-08-01 10:19
That sounds like expected behavior. The published deliveries will be distributed between the two consumers. Each delivery will be consumed by exactly one consumer. So each consumer will consume roughly half of the published deliveries.

**Comment by NikhilRyan** [comment] 2023-08-01 11:46
I think there is a confusion on my end on how to use it properly with multiple consumers. Is there any public repo or gist where I can see the implementation apart from the one provided in this repo.
